version: "3.7"

services:
  postgres:
    image: postgres:14-alpine
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=P@ssw0rd
    ports:
      - 5432:5432
    networks:
      - coffeeshop-network

  product:
    build: 
      context: .
      dockerfile: ./docker/Dockerfile-product
    container_name: product
    image: go-coffeeshop-product
    environment:
      APP_NAME: 'product-service in docker'
    ports:
      - 8080:8080
    depends_on:
      - postgres

networks:
  coffeeshop-network: