app:
  name: 'counter-service'
  version: '1.0.0'

http:
  host: '0.0.0.0'
  port: 5002

postgres:
  pool_max: 2
  url: postgres://postgres:P@ssw0rd@172.22.168.110:5432/counterdb_dev?sslmode=disable

rabbit_mq:
  url: amqp://guest:guest@172.22.168.110:5672/
  exchange: orders-exchange
  queue: orders-queue
  routing_key: orders-routing-key
  consumer_tag: orders-consumer

logger:
  log_level: 'debug'
  rollbar_env: 'counter-service'