app:
  name: 'counter-service'
  version: '1.0.0'

http:
  host: '0.0.0.0'
  port: 5002

rabbit_mq:
  url: amqp://guest:guest@172.28.191.206:5672/

logger:
  log_level: 'debug'
  rollbar_env: 'counter-service'