app:
  name: 'kitchen-service'
  version: '1.0.0'

http:
  host: '0.0.0.0'
  port: 5004

rabbit_mq:
  url: amqp://guest:guest@172.28.255.101:5672/

logger:
  log_level: 'debug'
  rollbar_env: 'kitchen-service'